version: 'RockLib.Messaging.SNS.{build}.0.0-ci'
image: Visual Studio 2022
configuration: Release
only_commits:
  files:
  - RockLib.Messaging.SNS/
  - Tests/RockLib.Messaging.SNS.Tests/
before_build:
- ps: |
    # The path to the solution to restore.
    $sln_path = "RockLib.Messaging.SNS\RockLib.Messaging.SNS.sln"
    
    # The path to the main csproj file. It will be patched during the build.
    $csproj_path = "RockLib.Messaging.SNS\RockLib.Messaging.SNS.csproj"
    
    # The version of the build artifact's nuget package when created by CI builds.
    $ci_package_version = "$Env:appveyor_build_number.0.0-ci"
    
    # This before_build script does three things:
    #
    # 1) Synchronize the AppVeyor build version and the csproj's package version.
    #   a) If the current build is a deploy build*, update the AppVeyor build version to match
    #      the csproj's nuget package version.
    #   b) If the current build is a CI build*, update the csproj's package version to match
    #      the AppVeyor build version.
    # 2) Set an AppVeyor build variable named 'csproj_build_version' to the csproj's package version.
    #    This value is used by deploy providers to determine whether the current commit should be deployed.
    # 3) Restore packages for the sln. .NET Standard libraries won't build without restoring first.
    #
    # *The current build is a deploy build if the 'appveyor_repo_tag' variable is 'true' and the
    #  'appveyor_repo_tag_name' variable is the the value of the 'csproj_build_version' variable, as set in
    #  #2 above. Otherwise, the current build is a CI build.
    
    function Get-Csproj-Build-Version ($csproj)
    {
        $package_id = $csproj.SelectSingleNode("/Project/PropertyGroup/PackageId").InnerText
        $package_version = $csproj.SelectSingleNode("/Project/PropertyGroup/PackageVersion").InnerText
        Return "$package_id.$package_version"
    }

    function Synchronize-AppVeyor-And-Csproj-Versions ($csproj)
    {
        $csproj_build_version = Get-Csproj-Build-Version $csproj

        If ($Env:appveyor_repo_tag -eq "true" -AND $Env:appveyor_repo_tag_name -eq $csproj_build_version) {
            # If this is a deploy build, update the AppVeyor build version to match the csproj's package version.
            Update-AppVeyorBuild -Version $csproj_build_version
        } else {
            # Else, update the csproj's package version to match the AppVeyor build version.
            $package_version_node = $csproj.SelectSingleNode("/Project/PropertyGroup/PackageVersion")
            $package_version_node.InnerText = $ci_package_version
        }
    }
    
    function Set-Csproj-Build-Version-Variable ($csproj)
    {
        $csproj_build_version = Get-Csproj-Build-Version $csproj
        Set-AppVeyorBuildVariable -Name "csproj_build_version" -Value $csproj_build_version
    }

    # The $csproj xml object contains the contents of the csproj file.
    $csproj = [xml](Get-Content $csproj_path)

    Synchronize-AppVeyor-And-Csproj-Versions $csproj
    Set-Csproj-Build-Version-Variable $csproj

    # Patch the csproj file with the modified xml object after all changes have been made.
    $csproj.Save((Get-Item $csproj_path))

    nuget restore $sln_path
build:
  project: RockLib.Messaging.SNS/RockLib.Messaging.SNS.sln
  verbosity: minimal
artifacts:
- path: '**/$(csproj_build_version).nupkg'
deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: $(appveyor_repo_commit_message)
  description: 'A changelog is available at https://github.com/RockLib/RockLib.Messaging/blob/main/RockLib.Messaging.SNS/CHANGELOG.md.'
  auth_token:
    secure: gglgEqQVi2MuIUl8g8rS6jb5r8sgr0PYa4qXq9XaAGeAJ+oAEFmlNFFw/jgX8hQr
  on:
    appveyor_repo_tag: true
    appveyor_repo_tag_name: $(csproj_build_version)
- provider: NuGet
  api_key:
    secure: A/s5F7VfxuaDqSjD8sti01zN7/9bZ5+9A/IpohDeZgpWY0cESCbw0NVFbYbmUoXc
  on:
    appveyor_repo_tag: true
    appveyor_repo_tag_name: $(csproj_build_version)
notifications:
- provider: Email
  to:
  - rocklibsupport@rocketmortgage.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
